const fs = require('fs');
let content = fs.readFileSync('src/App.tsx', 'utf8');

// Look for rendering loop
// "currentLines.forEach((lineSegments, lIdx) => {"
// If seg.type === 'image' and seg.isInline, we need to draw it inline!
const renderInlineImage = `
           if (seg.type === 'image') {
               if (!seg.isInline) {
                   const img = new Image();
                   img.crossOrigin = "anonymous";
                   img.src = seg.src!;
                   img.onload = () => { ctx.drawImage(img, cursorX, cursorY, seg.width!, seg.height!); };
                   cursorY += seg.height! + 20;
               } else {
                   const img = new Image();
                   img.crossOrigin = "anonymous";
                   img.src = seg.src!;
                   const renderX = cursorX;
                   const renderY = cursorY - seg.height! / 2; // Adjust for vertical alignment
                   img.onload = () => { ctx.drawImage(img, renderX, renderY, seg.width!, seg.height!); };
                   cursorX += seg.width! + (spacingFactor * SCALE);
               }
               return;
           }
`;

content = content.replace(/if \(seg\.type === 'image'\) \{[\s\S]*?return;\n           \}/, renderInlineImage);

// Another issue: "Formula being overlapping with other text."
// "Not aligning correctly."
// The inline image `cursorY` adjustment (`cursorY - seg.height! / 2`) might not be right.
// Text baseline is usually bottom or alphabetic. `cursorY` is usually the top or bottom of the line?
// `cursorY` in this app is updated by `maxLineHeight`.
// "Most of the formula being strike through."
// Wait, the strike-through effect might be `ctx.strokeText(seg.text, ...)` running on an image? No, image returns early.
// Oh, the strike-through effect might be because of the scan lines on lined paper! "lined" paper draws lines across the page.
// The image itself has a transparent background (from html2canvas `{backgroundColor: null}`).
// But maybe the math is drawn over the lines, which makes it look strike through. Or maybe the html2canvas has artifacts.
// Let's modify `html2canvas` to use a white background or no background but ensure the stroke isn't going through.
// Actually, handwriting text goes OVER the lines too, but it's thin. Formulas have fractions (horizontal lines), so it looks messy.
// We can just accept the lines behind it or give it a slight white background. Let's add a white background to math.
// Wait, user says "Most of the formula being strike through". They probably mean the `strike-through` format is applied?
// "Most of the formula being strike through": Is the HTML `seg.isUnderline` or something applied?
// Let's check where underline/strikethrough is applied. The parser parses `<U>` tags for underline.
// If the image is generated by `html2canvas`, it might be catching `<del>` or `<strike>`?
// Or maybe the *line* in the paper background is passing right through the middle of the formula, making the fraction bar look confusing or striking it through?
// If we set `backgroundColor: "#fffdf0"` (paper color) in html2canvas, the formula will hide the paper lines behind it! That solves the strike-through effect!

// Also: "img.style.height" in `triggerParse`:
// `img.style.height = (canvas.height / 2) + 'px';`
// But we need `img.width` and `img.height` properties set for the parser to read them correctly! `imgEl.width` reads the attribute, not style.

content = content.replace(/img\.style\.height = \(canvas\.height \/ 2\) \+ 'px';/g, `
            img.width = canvas.width / 2;
            img.height = canvas.height / 2;
            img.style.height = (canvas.height / 2) + 'px';
            img.style.width = (canvas.width / 2) + 'px';
`);

content = content.replace(/backgroundColor: null/g, `backgroundColor: isDarkMode ? "#0f172a" : "#fffdf0"`); // wait, html2canvas is run on DOM which is dark or light, but the PDF is always light (or based on scanEffect).
// The canvas is `#fffdf0` or `#f4f4f4`. Let's just use `#fffdf0` (blank paper) so it blocks the lines.
content = content.replace(/\{ backgroundColor: isDarkMode \? "#0f172a" : "#fffdf0", scale: 2 \}/g, `{ backgroundColor: scanEffect ? "#f4f4f4" : "#fffdf0", scale: 2 }`);

fs.writeFileSync('src/App.tsx', content);
