name: Trigger APK Build

on:
  push:
    branches:
      - main # Or whichever branch you want to trigger the APK build from
      - 'android-build-*'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Remote Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_PAT }}
          repository: Mr-vabs/testApp
          event-type: trigger-apk-build
          client-payload: '{"sha": "${{ github.sha }}"}'
